spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_chat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 添加HikariCP连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # 添加CORS配置，允许跨域访问
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      max-age: 3600
    resources:
      static-locations: classpath:/static/

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  # MVC配置
  mvc:
    static-path-pattern: /static/**

server:
  port: 8090
  servlet:
    context-path: /api
  # 添加以下配置，使服务器绑定到所有网络接口
  address: 0.0.0.0

# JWT配置
jwt:
  secret: your_very_secure_secret_key_at_least_32_bytes_long
  expiration: 8640000

